from typing import Protocol, Self


class MathField(Protocol):
    def __add__(self, other: Self) -> Self: ...
    def __sub__(self, other: Self) -> Self: ...
    def __mul__(self, other: Self) -> Self: ...
    def __truediv__(self, other: Self) -> Self: ...

    def __pow__(self, power: int) -> Self: ...

    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

    def get_zero(self) -> Self: ...