from typing import Protocol, TypeVar, Any

T = TypeVar('T', bound='MathField')


class MathField(Protocol):
    def __add__(self, other: T) -> T: ...
    def __sub__(self, other: T) -> T: ...
    def __mul__(self, other: T) -> T: ...
    def __truediv__(self, other: T) -> T: ...

    def __eq__(self, other: T) -> bool: ...
    def __ne__(self, other: T) -> bool: ...

    def get_zero(self) -> T: ...